version: '2'
services:
    web:
        build: .
        image: colournaming
        ports:
        - "5000:5000"
        environment:
        - COLOURNAMING_CFG=/app/docker.cfg
        - PYTHONPATH=/app
        - FLASK_DEBUG=0
        command: run -h 0.0.0.0 -p 5000
    postgres:
        image: "postgres"
        environment:
        - POSTGRES_PASSWORD=testpass
