name: Run tests

on: [pull_request]

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: testpass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Setup python
        run: uv python install
      - name: Install dependencies
        run: uv sync --locked --extra dev
      - name: Lint with ruff
        run: uv run ruff check colournaming
      - name: Initialise database
        run: uv run flask initdb
        env:
          FLASK_ENV: development
          COLOURNAMING_CFG: ${{ github.workspace }}/github.cfg
      - name: Test with pytest
        run: uv run flask test
        env:
          FLASK_ENV: development
          COLOURNAMING_CFG: ${{ github.workspace }}/github.cfg
